Repository Podobat/PodoIt, pull requests merged in 2025-08, with the labels that each got.

#3 feat: #1 - SwiftData 모델 생성
  PodoIt/App/SceneDelegate.swift
  PodoIt/Data/SwiftDataManager.swift
  PodoIt/DesignSystem/Color/ColorBook.swift
  PodoIt/DesignSystem/Color/GrayColor.swift
  PodoIt/DesignSystem/Color/PaletteApp.swift
  PodoIt/DesignSystem/Color/VioletColor.swift
  PodoIt/DesignSystem/Font/PodoItFont.swift
  PodoIt/DesignSystem/Font/PodoItFontStyle.swift
  PodoIt/Models/StatsModel.swift
  PodoIt/Models/TimerModel.swift
Labels: ✨ feat, 🦊 이든, 🔗 SwiftData

#11 chore: #10 - 폰트 스타일 수정
  PodoIt/DesignSystem/Font/PodoItFontStyle.swift
Labels: 🧹 chore, 🐤 가현

#16 feat: #14 - 타이머 추가 페이지 UI 구성
  PodoIt/Scenes/Timer/View/TimerEditViewController.swift
  PodoIt/Scenes/Timer/View/TimerViewController.swift
  PodoIt/Scenes/Timer/ViewComponent/EmptyStateView.swift
  PodoIt/Scenes/Timer/ViewComponent/TimerHeaderView.swift
  PodoIt/Support/Extensions/UITextField+Padding.swift
Labels: ✨ feat, 🐤 가현, 📱 UI/UX

#15 feat: #4 - 설정 화면 UI 구성
  PodoIt/Scenes/Setting/Model/SettingModel.swift
  PodoIt/Scenes/Setting/SettingViewController.swift
  PodoIt/Scenes/Setting/View/SettingFooterView.swift
  PodoIt/Scenes/Setting/View/SettingHeaderView.swift
  PodoIt/Scenes/Setting/View/SettingViewCell.swift
  PodoIt/Scenes/Setting/View/SettingViewController.swift
  PodoIt/Scenes/Setting/ViewModel/SettingViewModel.swift
Labels: ✨ feat, 🐶 광용, 📱 UI/UX

#22 feat: #18 - TimerCell UI 구현
  PodoIt/Resources/Images.xcassets/play_fill.imageset/Contents.json
  PodoIt/Resources/Images.xcassets/play_fill.imageset/icon.pdf
  PodoIt/Scenes/Timer/View/TimerEditViewController.swift
  PodoIt/Scenes/Timer/View/TimerViewController.swift
  PodoIt/Scenes/Timer/ViewComponent/TimerCell.swift
Labels: ✨ feat, ♻️ refactor, 🐤 가현, 📱 UI/UX

#36 feat: #24 - 목표 집중 시간 Picker UI 구현
  PodoIt/DesignSystem/Font/PodoItFontStyle.swift
  PodoIt/Scenes/Timer/View/TimerEditViewController.swift
  PodoIt/Scenes/Timer/View/TimerViewController.swift
Labels: ✨ feat, 🧹 chore, 🐤 가현, 📱 UI/UX

#38 feat: #2 - ViewModel, CRUD 구현
  PodoIt.xcodeproj/project.pbxproj
  PodoIt/App/SceneDelegate.swift
  PodoIt/Data/Dependencies.swift
  PodoIt/Data/SwiftDataManager.swift
  PodoIt/Scenes/RootScene/MainTabBarController.swift
  PodoIt/Scenes/Timer/Repository/TimerRepository.swift
  PodoIt/Scenes/Timer/View/TimerEditViewController.swift
  PodoIt/Scenes/Timer/View/TimerViewController.swift
  PodoIt/Scenes/Timer/ViewModel/TimerEditViewModel.swift
  SwiftDataTimerRepositoryTests/SwiftDataTimerRepositoryTests.swift
Labels: ✨ feat, ✅ add, 🐤 가현, 🔗 SwiftData

#54 feat: #25 - 수정 페이지, 커스텀 알럿 구현
  PodoIt/Resources/Images.xcassets/trash.imageset/Contents.json
  PodoIt/Resources/Images.xcassets/trash.imageset/trash-2.png
  PodoIt/Scenes/Timer/View/TimerEditViewController.swift
  PodoIt/Support/UI/PodoAlertController.swift
Labels: ✨ feat, 🧹 chore, ♻️ refactor, 🐤 가현
