Repository Podobat/PodoIt, pull requests merged in 2025-09, with the labels that each got.

#67 feat: #56 - Rx기반의 타이머 실행/일시정지/재개/정지 로직 구현
  PodoIt/Scenes/TimerRun/View/Sections/ButtonSectionView.swift
  PodoIt/Scenes/TimerRun/View/Sections/TimerSectionView.swift
  PodoIt/Scenes/TimerRun/View/TimerRunViewController.swift
  PodoIt/Scenes/TimerRun/ViewModel/TimerRunViewModel.swift
Labels: ✨ feat, 🐶 광용, 🔗 SwiftData

#72 feat: #66 - 통계 화면 카테고리 선택 모달 구현
  PodoIt/Models/StatsModel.swift
  PodoIt/Scenes/Stats/View/StatsViewController.swift
  PodoIt/Scenes/Stats/View/ViewSubClasses/Header/StatsCategoryModel.swift
  PodoIt/Scenes/Stats/View/ViewSubClasses/Header/StatsHeaderView.swift
  PodoIt/Scenes/Stats/View/ViewSubClasses/Header/StatsSheetViewController.swift
  PodoIt/Scenes/Stats/View/ViewSubClasses/Summary/List/StatsCollectionViewCell.swift
  PodoIt/Support/Extensions/String+MaxLength.swift
Labels: ✨ feat, 🦊 이든, 📱 UI/UX

#75 feat: #44 - 타이머 UI/작동 및 숫자 고정폭(monospaced digits) 적용
  PodoIt/DesignSystem/Font/PodoItFontStyle.swift
  PodoIt/Scenes/TimerRun/Model/TimerSessionState.swift
  PodoIt/Scenes/TimerRun/View/Sections/ButtonSectionView.swift
  PodoIt/Scenes/TimerRun/View/Sections/HeaderSectionView.swift
  PodoIt/Scenes/TimerRun/View/Sections/MiddleSectionView.swift
  PodoIt/Scenes/TimerRun/View/Sections/TimerSectionView.swift
  PodoIt/Scenes/TimerRun/View/TimerRunViewController.swift
  PodoIt/Scenes/TimerRun/ViewModel/TimerRunViewModel.swift
Labels: ✨ feat, ♻️ refactor, 🐶 광용, 📱 UI/UX

#80 feat: #73 - 통계 화면 카테고리 선택 Sheet 연동 및 갱신
  PodoIt/Data/SwiftDataManager.swift
  PodoIt/Scenes/Stats/View/StatsViewController.swift
  PodoIt/Scenes/Stats/View/ViewSubClasses/Calendar/CalendarCell.swift
  PodoIt/Scenes/Stats/View/ViewSubClasses/Calendar/CalendarView.swift
  PodoIt/Scenes/Stats/View/ViewSubClasses/Header/StatsCategoryModel.swift
  PodoIt/Scenes/Stats/View/ViewSubClasses/Summary/StatsCollectionViewCell.swift
  PodoIt/Scenes/Stats/View/ViewSubClasses/Summary/StatsCustomSegmentedControl.swift
  PodoIt/Scenes/Stats/ViewModel/StatsViewModel.swift
Labels: ✨ feat, 🦊 이든, 🔗 SwiftData, 📱 UI/UX

#85 chore: #84 - SwiftDataTimerRepositoryTest 삭제
  PodoIt.xcodeproj/project.pbxproj
  SwiftDataTimerRepositoryTests/SwiftDataTimerRepositoryTests.swift
Labels: 🧹 chore, 🐤 가현

#87 add: #86 - Green 컬러 추가
  PodoIt/DesignSystem/Color/GreenColor.swift
  PodoIt/Resources/Colors.xcassets/Green/Contents.json
  PodoIt/Resources/Colors.xcassets/Green/green100.colorset/Contents.json
  PodoIt/Resources/Colors.xcassets/Green/green200.colorset/Contents.json
  PodoIt/Resources/Colors.xcassets/Green/green300.colorset/Contents.json
  PodoIt/Resources/Colors.xcassets/Green/green400.colorset/Contents.json
  PodoIt/Resources/Colors.xcassets/Green/green50.colorset/Contents.json
  PodoIt/Resources/Colors.xcassets/Green/green500.colorset/Contents.json
  PodoIt/Resources/Colors.xcassets/Green/green600.colorset/Contents.json
  PodoIt/Resources/Colors.xcassets/Green/green700.colorset/Contents.json
  PodoIt/Resources/Colors.xcassets/Green/green800.colorset/Contents.json
  PodoIt/Resources/Colors.xcassets/Green/green900.colorset/Contents.json
  PodoIt/Resources/Colors.xcassets/Green/green950.colorset/Contents.json
Labels: ✅ add, 🐶 광용

#89 chore: #88 - 1분으로 테스트 시간
  PodoIt/Scenes/Timer/View/TimerEditViewController.swift
  PodoIt/Scenes/Timer/ViewComponent/TimerCell.swift
Labels: 🧹 chore, 🐤 가현, 🔗 SwiftData, 📱 UI/UX

#90 feat: #47 - 휴식 모드 타이머 등 UI 업데이트
  PodoIt.xcodeproj/project.pbxproj
  PodoIt.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PodoIt/Resources/Images.xcassets/circle-check.imageset/Contents.json
  PodoIt/Resources/Images.xcassets/circle-check.imageset/circle-check.pdf
  PodoIt/Resources/Images.xcassets/cup.imageset/Contents.json
  PodoIt/Resources/Images.xcassets/cup.imageset/Shape.pdf
  PodoIt/Scenes/TimerRun/Model/TimerSessionState.swift
  PodoIt/Scenes/TimerRun/View/Sections/TimerSectionView.swift
  PodoIt/Scenes/TimerRun/View/TimerRunViewController.swift
  PodoIt/Scenes/TimerRun/ViewModel/TimerRunViewModel.swift
Labels: ✨ feat, 🐶 광용, 📱 UI/UX

#92 chore: #81 - 셀 5개 도달 시 버튼 비활성화
  PodoIt/Scenes/Timer/View/TimerViewController.swift
Labels: 🧹 chore, 🐤 가현, 📱 UI/UX

#103 chore: #39 - 셀 생성 시 최신 순으로 정렬 되도록
  PodoIt/Data/SwiftDataManager.swift
  PodoIt/Models/TimerModel.swift
Labels: 🧹 chore, 🐤 가현, 🔗 SwiftData

#105 docs: #79 - README 초본 작성
  README.md
Labels: ✅ add, 📋 docs, 🐶 광용

#113 chore: #112 - Team 이름과 bundle identifer 변경
  PodoIt.xcodeproj/project.pbxproj
  PodoIt/App/ko.lproj/LaunchScreen.strings
Labels: 🧹 chore, 🐶 광용

#116 add: #115 - 앱 아이콘 추가
  PodoIt/Resources/Images.xcassets/AppIcon.appiconset/Contents.json
  PodoIt/Resources/Images.xcassets/AppIcon.appiconset/Logo 1.png
  PodoIt/Resources/Images.xcassets/AppIcon.appiconset/Logo 2.png
  PodoIt/Resources/Images.xcassets/AppIcon.appiconset/Logo.png
Labels: ✅ add, 🐶 광용

#118 chore: #117 - 앱 아이콘 모서리 없는걸로 수정
  PodoIt/Resources/Images.xcassets/AppIcon.appiconset/Logo 1.png
  PodoIt/Resources/Images.xcassets/AppIcon.appiconset/Logo 2.png
  PodoIt/Resources/Images.xcassets/AppIcon.appiconset/Logo.png
Labels: 🧹 chore, 🐶 광용

#120 feat: #68 - appid 등록 후 셀 주석 해제
  PodoIt/Scenes/Setting/View/Setting/SettingViewController.swift
  PodoIt/Scenes/Setting/ViewModel/SettingViewModel.swift
Labels: ✨ feat, 🐶 광용, 📱 UI/UX

#121 chore: #119 - 앱 설정 수정
  PodoIt.xcodeproj/project.pbxproj
Labels: 🧹 chore, 🦊 이든

#124 feat: #49 - 타이머 종료 시 커스텀 알럿 및 중앙 정렬, 선택 구간 볼드 헬퍼 추가
  PodoIt/Scenes/TimerRun/View/TimerRunViewController.swift
  PodoIt/Support/UI/PodoAlertController.swift
Labels: ✨ feat, 🐶 광용, 📱 UI/UX

#126 refactor: #125 - 타이머 실행 부분 로직들 리팩토링
  PodoIt/Resources/Images.xcassets/focus.imageset/Contents.json
  PodoIt/Resources/Images.xcassets/focus.imageset/focus.pdf
  PodoIt/Resources/Images.xcassets/rest.imageset/Contents.json
  PodoIt/Resources/Images.xcassets/rest.imageset/rest.pdf
  PodoIt/Scenes/TimerRun/Model/TimerSessionState.swift
  PodoIt/Scenes/TimerRun/View/Sections/AnimationSectionView.swift
  PodoIt/Scenes/TimerRun/View/Sections/ButtonSectionView.swift
  PodoIt/Scenes/TimerRun/View/Sections/HeaderSectionView.swift
  PodoIt/Scenes/TimerRun/View/Sections/ProgressRestSectionView.swift
  PodoIt/Scenes/TimerRun/View/Sections/TimerSectionView.swift
  PodoIt/Scenes/TimerRun/View/TimerRunViewController.swift
  PodoIt/Scenes/TimerRun/ViewModel/TimerRunViewModel.swift
Labels: ♻️ refactor, 🐶 광용

#135 chore: #104 - 카드 쉐도우 추가 + corner radius 값 수정
  PodoIt/Scenes/Timer/ViewComponent/TimerCell.swift
Labels: 🧹 chore, 🐤 가현, 📱 UI/UX

#137 chore: #136 - 집중 시간 하드코딩 -> 실행한 시간 받아오기
  PodoIt/Scenes/Timer/View/TimerViewController.swift
  PodoIt/Scenes/Timer/ViewComponent/TimerHeaderView.swift
Labels: 🧹 chore, 🐤 가현, 📱 UI/UX

#140 chore: #139 - 이미지 변경 및 Alert Title 변경
  PodoIt/Resources/Images.xcassets/focus.imageset/Contents.json
  PodoIt/Resources/Images.xcassets/focus.imageset/focus.pdf
  PodoIt/Resources/Images.xcassets/rest.imageset/Contents.json
  PodoIt/Resources/Images.xcassets/rest.imageset/rest.pdf
  PodoIt/Support/UI/PodoAlertController.swift
Labels: 🧹 chore, 🐶 광용, 📱 UI/UX

#142 feat: #111 - 캘린더 집중 시간별 색상 표시
  PodoIt/DesignSystem/Font/PodoItFontStyle.swift
  PodoIt/Scenes/Stats/View/StatsViewController.swift
  PodoIt/Scenes/Stats/ViewComponent/Calendar/CalendarCell.swift
  PodoIt/Scenes/Stats/ViewComponent/Calendar/CalendarColorView.swift
  PodoIt/Scenes/Stats/ViewComponent/Calendar/CalendarView.swift
  PodoIt/Scenes/Stats/ViewComponent/Header/StatsHeaderView.swift
  PodoIt/Scenes/Stats/ViewComponent/Summary/StatsCustomSegmentedControl.swift
  PodoIt/Scenes/Stats/ViewComponent/Summary/StatsSummaryView.swift
  PodoIt/Scenes/Stats/ViewModel/StatsViewModel.swift
  PodoIt/Scenes/Timer/ViewComponent/TimerHeaderView.swift
Labels: ✨ feat, 🦊 이든, 🔗 SwiftData, 📱 UI/UX

#145 feat: #42 - 타이머 UserDefaults로 상태 복원
  PodoIt/App/SceneDelegate.swift
  PodoIt/AppSettings/AudioSettings.swift
  PodoIt/Resources/Info.plist
  PodoIt/Resources/PrivacyInfo.xcprivacy
  PodoIt/Scenes/RootScene/MainTabBarController.swift
  PodoIt/Scenes/TimerRun/Model/TimerSessionState.swift
  PodoIt/Scenes/TimerRun/Model/TimerSessionUDSnapshot.swift
  PodoIt/Scenes/TimerRun/View/TimerRunViewController.swift
  PodoIt/Scenes/TimerRun/ViewModel/TimerRunViewModel.swift
Labels: ✨ feat, 🐶 광용, 📱 UI/UX

#146 feat: #69 - 다크모드 비활성화
  PodoIt/Resources/Info.plist
Labels: ✨ feat

#164 refactor: #161 - UUID를 통한 fetch 대신, timer model 직접 주입으로 리팩토링
  PodoIt/Scenes/RootScene/MainTabBarController.swift
  PodoIt/Scenes/Timer/View/TimerViewController.swift
  PodoIt/Scenes/TimerRun/View/TimerRunViewController.swift
  PodoIt/Scenes/TimerRun/ViewModel/TimerRunViewModel.swift
Labels: ♻️ refactor, 🐶 광용

#175 chore: #174 - 타이머 라벨 텍스트 변경
  PodoIt/Support/UI/PodoAlertController.swift
Labels: 🧹 chore, 🐶 광용, 📱 UI/UX

#178 chore: #177 - 텍스트 필드 최대 글자수 표시
  PodoIt/Scenes/Timer/View/TimerEditViewController.swift
Labels: 🧹 chore, 🐤 가현, 📱 UI/UX

#183 feat: #176 - 타이머 음소거 버튼에 토스트 Alert 추가
  PodoIt/Resources/Images.xcassets/circle-bang.imageset/Contents.json
  PodoIt/Resources/Images.xcassets/circle-bang.imageset/circle-bang.pdf
  PodoIt/Resources/Images.xcassets/circle-check-green.imageset/Contents.json
  PodoIt/Resources/Images.xcassets/circle-check-green.imageset/circle-check-green.pdf
  PodoIt/Scenes/Timer/View/TimerEditViewController.swift
  PodoIt/Scenes/TimerRun/View/TimerRunViewController.swift
  PodoIt/Support/Extensions/UIViewController+Toast.swift
Labels: ✨ feat, 🐶 광용, 📱 UI/UX

#187 chore: #185 - 타이머 목록 페이지 위 날짜, 요일까지 표시
  PodoIt/Scenes/Timer/ViewComponent/TimerHeaderView.swift
Labels: 🧹 chore, 🐤 가현, 📱 UI/UX

#188 feat: #51 - 타이머 Lottie 애니메이션 적용
  PodoIt.xcodeproj/project.pbxproj
  PodoIt.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PodoIt/Resources/Animations/Marketing.lottie
  PodoIt/Resources/Animations/focus.lottie
  PodoIt/Scenes/TimerRun/View/Sections/AnimationSectionView.swift
  PodoIt/Scenes/TimerRun/View/Sections/ProgressRestSectionView.swift
  PodoIt/Scenes/TimerRun/View/TimerRunViewController.swift
Labels: ✨ feat, 🐶 광용, 📱 UI/UX

#189 chore: #186 - 키보드 위에 저장하기 버튼 뜨도록 수정
  PodoIt/Scenes/Timer/View/TimerEditViewController.swift
Labels: 🧹 chore, 🙋🏻 Questing, 🐤 가현, 📱 UI/UX

#193 chore: #179 - 통계 카테고리 선택 sheet 잘리는 버그 수정
  PodoIt/Scenes/Stats/ViewComponent/Header/SheetTransitionDelegate.swift
  PodoIt/Scenes/Stats/ViewComponent/Header/StatsSheetViewController.swift
Labels: 🐛 fix, 🦊 이든, 📱 UI/UX

#195 chore: #191 - 휴식 lottie 파일 변경하여 적용
  PodoIt/Resources/Animations/Marketing.lottie
  PodoIt/Resources/Animations/rest.lottie
  PodoIt/Scenes/TimerRun/View/Sections/AnimationSectionView.swift
Labels: 🧹 chore, 🐶 광용, 📱 UI/UX

#197 fix: #180 - 텍스트 잘리는 버그 수정
  PodoIt/Scenes/Stats/ViewComponent/Header/StatsHeaderView.swift
Labels: 🐛 fix, 🦊 이든, 📱 UI/UX

#198 feat: #184 - 텍스트 필드 글자 제한 토스트 알럿
  PodoIt/Scenes/Timer/View/TimerEditViewController.swift
  PodoIt/Support/Extensions/UIViewController+Toast.swift
Labels: ✨ feat, 🐤 가현, 📱 UI/UX

#199 feat: #196 - 1분 기준으로 Alert 분기
  PodoIt/Scenes/TimerRun/View/TimerRunViewController.swift
  PodoIt/Scenes/TimerRun/ViewModel/TimerRunViewModel.swift
  PodoIt/Support/UI/PodoAlertController.swift
Labels: ✨ feat, 🐶 광용, 📱 UI/UX

#208 feat: #201 - 스와이프로 타이머 셀 삭제
  PodoIt/Scenes/Timer/View/TimerViewController.swift
  PodoIt/Scenes/Timer/ViewComponent/TimerCell.swift
Labels: ✨ feat, 🐤 가현, 📱 UI/UX

#211 chore: #210 - trash png -> pdf로 변경
  PodoIt/Resources/Images.xcassets/trash.imageset/Contents.json
  PodoIt/Resources/Images.xcassets/trash.imageset/trash-2 (1).pdf
  PodoIt/Resources/Images.xcassets/trash.imageset/trash-2.png
Labels: 🧹 chore, 🐤 가현

#217 chore: #214 - 셀 주변에 빨간색 비치는 현상 해결
  PodoIt/Scenes/Timer/ViewComponent/TimerCell.swift
Labels: 🧹 chore, 🐛 fix, 🐤 가현, 📱 UI/UX

#220 chore: #219 - 1.1.0버전 빌드 10
  PodoIt.xcodeproj/project.pbxproj
Labels: 🧹 chore, 🐶 광용

#226 docs: #223 - ver 1.1.0버전 README 수정
  README.md
Labels: 📋 docs, 🦊 이든
